### ISSUE TITLE
issues second screen

### ISSUE THREAD

**Issue by panda72989** [SegoCode/AutoWall#23]
try to open the second screen and start blink

**Comment by SegoCode** [comment]
#### Before Submitting a Bug Report

A good bug report shouldn't leave others needing to chase you up for more information. Therefore, we ask you to investigate carefully, collect information and describe the issue in detail in your report. Please complete the following steps in advance to help us fix any potential bug as fast as possible.

- Make sure that you are using the latest version.
- Determine if your bug is really a bug and not an error on your side e.g. using incompatible environment components/versions. If you are looking for support, you might want to check [this section](#i-have-a-question).
- To see if other users have experienced (and potentially already solved) the same issue you are having, check if there is not already a bug report existing for your bug or error in the [Issues](https://github.com/SegoCode/AutoWall/issues).
- Collect information about the bug:
  - OS, Platform and Version (Windows).
  - Version of the AutoWall.
  - Any software in seems relevant in background.
  - Can you reliably reproduce the issue? And can you also reproduce it with older versions?

#### How Do I Submit a Good Bug Report?

We use GitHub issues to track bugs and errors. If you run into an issue with the project:

- Open an [Issue](https://github.com/SegoCode/AutoWall/issues/new). (Since we can't be sure at this point whether it is a bug or not, we ask you not to talk about a bug yet and not to label the issue.)
- Explain the behavior you would expect and the actual behavior.
- Please provide as much context as possible and describe the *reproduction steps* that someone else can follow to recreate the issue on their own.

Once it's filed:

- I will label the issue accordingly.
- I will try to reproduce the issue with your provided steps. If there are no reproduction steps or no obvious way to reproduce the issue
- If i will able to reproduce the issue, it will be marked with a related tag, and the issue will be left to be implemented by someone.
